/**
 * Globally unique identity of one persisted message. Immutable across every
 * retry/redelivery of that message. Used as the outbox primary key and the
 * inbox deduplication key.
 */
export type MessageId = string & { readonly __brand: 'MessageId' };

/**
 * Stable identity derived from (messageId, effectName), forwarded to
 * external providers that support idempotent requests (e.g.
 * `Stripe-Idempotency-Key`). Never generated by the caller.
 */
export type IdempotencyKey = string & { readonly __brand: 'IdempotencyKey' };

/**
 * Generates `MessageId`s. Encoding (e.g. UUIDv7) is an infrastructure
 * concern deliberately kept out of core, and left to the concrete adapter.
 */
export interface IdGenerator {
  newMessageId(): MessageId;
}
