export const RELIABLE_OUTBOX_STORE = Symbol('RELIABLE_OUTBOX_STORE');
export const RELIABLE_INBOX_STORE = Symbol('RELIABLE_INBOX_STORE');
export const RELIABLE_MODULE_OPTIONS = Symbol('RELIABLE_MODULE_OPTIONS');
